version: "4"
name: fullstackhero
services:
  webapi:
    image: ghcr.io/fullstackhero/webapi:latest
    pull_policy: always
    container_name: webapi
    networks:
      - fullstackhero
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5010
      - ASPNETCORE_HTTPS_PORT=5100
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - DatabaseOptions__ConnectionString=Server=postgres;Port=5433;Database=fullstackhero;User Id=pgadmin;Password=pgadmin
      - DatabaseOptions__Provider=postgresql
      - JwtOptions__Key=QsJbczCNysv/5SGh+U7sxedX8C07TPQPBdsnSDKZ/aE=
      - HangfireOptions__Username=admin
      - HangfireOptions__Password=Secure1234!Me
      - MailOptions__From=mukesh@fullstackhero.net
      - MailOptions__Host=smtp.ethereal.email
      - MailOptions__Port=587
      - MailOptions__UserName=sherman.oconnell47@ethereal.email
      - MailOptions__Password=KbuTCFv4J6Fy7256vh
      - MailOptions__DisplayName=Mukesh Murugan
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5100:5100
      - 5010:5010
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - fullstackhero
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdata:

networks:
  fullstackhero:
    name: fullstackhero
